[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x3372ba57a3cfe03a028b4f63d52cf83638acc54494ad3090d00b563ca2e0b0b"
transaction_hash = "0x1b278108b501eabac5cb6008e863489aedc00e00ac3960a0fd35c623cc6fcd9"
block_number = 14
seed = "dojo_starter_rpg"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x28081da70e2e54b8da9f2dea2f67849deaec7c1e23f53d8b697414caa1be7f"
class_hash = "0x318d3a5b81d565d582363847b20b3936cfed48690354439aa6a507f83150222"
original_class_hash = "0x318d3a5b81d565d582363847b20b3936cfed48690354439aa6a507f83150222"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter_rpg-actions-4afbdb7a.json"
reads = []
writes = [
    "dojo_starter_rpg-Player",
    "dojo_starter_rpg-Dungeon",
]
init_calldata = []
tag = "dojo_starter_rpg-actions"
systems = [
    "spawn",
    "move",
    "attack",
    "heal",
]
manifest_name = "dojo_starter_rpg-actions-4afbdb7a"

[[models]]
kind = "DojoModel"
class_hash = "0x3b8d4fef9b46617a99b9050200048edc7e522c4f388e23d262bd29f3e7eb53c"
original_class_hash = "0x3b8d4fef9b46617a99b9050200048edc7e522c4f388e23d262bd29f3e7eb53c"
abi = "manifests/dev/deployment/abis/models/dojo_starter_rpg-Dungeon-437fd4ba.json"
tag = "dojo_starter_rpg-Dungeon"
qualified_path = "rpg::models::index::dungeon"
manifest_name = "dojo_starter_rpg-Dungeon-437fd4ba"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "monster"
type = "u8"
key = false

[[models.members]]
name = "role"
type = "u8"
key = false

[[models.members]]
name = "damage"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "reward"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2cb22c61577afc5f6c2977f2c40f005aa67d96524cbb0e925607c23e10a718e"
original_class_hash = "0x2cb22c61577afc5f6c2977f2c40f005aa67d96524cbb0e925607c23e10a718e"
abi = "manifests/dev/deployment/abis/models/dojo_starter_rpg-Player-12268099.json"
tag = "dojo_starter_rpg-Player"
qualified_path = "rpg::models::index::player"
manifest_name = "dojo_starter_rpg-Player-12268099"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "mode"
type = "u8"
key = false

[[models.members]]
name = "role"
type = "u8"
key = false

[[models.members]]
name = "damage"
type = "u8"
key = false

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "gold"
type = "u16"
key = false

[[models.members]]
name = "score"
type = "u16"
key = false

[[models.members]]
name = "seed"
type = "felt252"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4b62eaf8033fe92627f262746bb8ee57dd8f932c92fea35fd3f3fefc18a573d"
original_class_hash = "0x4b62eaf8033fe92627f262746bb8ee57dd8f932c92fea35fd3f3fefc18a573d"
abi = "manifests/dev/deployment/abis/models/haiku-AttackEvent-7bdb02fd.json"
tag = "haiku-AttackEvent"
qualified_path = "rpg::components::playable::PlayableComponent::attack_event"
manifest_name = "haiku-AttackEvent-7bdb02fd"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "player_role"
type = "u8"
key = false

[[models.members]]
name = "player_mode"
type = "u8"
key = false

[[models.members]]
name = "player_health"
type = "u8"
key = false

[[models.members]]
name = "player_gold"
type = "u16"
key = false

[[models.members]]
name = "player_score"
type = "u16"
key = false

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "dungeon_monster"
type = "u8"
key = false

[[models.members]]
name = "dungeon_role"
type = "u8"
key = false

[[models.members]]
name = "dungeon_damage"
type = "u8"
key = false

[[models.members]]
name = "dungeon_health"
type = "u8"
key = false

[[models.members]]
name = "dungeon_reward"
type = "u16"
key = false

[[models.members]]
name = "has_defeated_dungeon"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1a7bcbecd271866164a7b7f95522d9de78ca6504878ad5cdd7c5b120aa22877"
original_class_hash = "0x1a7bcbecd271866164a7b7f95522d9de78ca6504878ad5cdd7c5b120aa22877"
abi = "manifests/dev/deployment/abis/models/haiku-HealEvent-4aa124a4.json"
tag = "haiku-HealEvent"
qualified_path = "rpg::components::playable::PlayableComponent::heal_event"
manifest_name = "haiku-HealEvent-4aa124a4"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "player_role"
type = "u8"
key = false

[[models.members]]
name = "player_mode"
type = "u8"
key = false

[[models.members]]
name = "player_health"
type = "u8"
key = false

[[models.members]]
name = "player_gold"
type = "u16"
key = false

[[models.members]]
name = "player_score"
type = "u16"
key = false

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "quantity"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6b105b639c0ab8d61032371216ec5ee155a983cc0451a469a827f33b76668e4"
original_class_hash = "0x6b105b639c0ab8d61032371216ec5ee155a983cc0451a469a827f33b76668e4"
abi = "manifests/dev/deployment/abis/models/haiku-MoveEvent-54195a34.json"
tag = "haiku-MoveEvent"
qualified_path = "rpg::components::playable::PlayableComponent::move_event"
manifest_name = "haiku-MoveEvent-54195a34"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "direction"
type = "u8"
key = false

[[models.members]]
name = "player_role"
type = "u8"
key = false

[[models.members]]
name = "player_mode"
type = "u8"
key = false

[[models.members]]
name = "player_health"
type = "u8"
key = false

[[models.members]]
name = "player_gold"
type = "u16"
key = false

[[models.members]]
name = "player_score"
type = "u16"
key = false

[[models.members]]
name = "player_name"
type = "felt252"
key = false

[[models.members]]
name = "new_dungeon_monster"
type = "u8"
key = false

[[models.members]]
name = "new_dungeon_role"
type = "u8"
key = false

[[models.members]]
name = "new_dungeon_damage"
type = "u8"
key = false

[[models.members]]
name = "new_dungeon_health"
type = "u8"
key = false

[[models.members]]
name = "new_dungeon_reward"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1db14cac86795ac0ff8dac3d7e426273d98e209007288169b9d8353bcbdd0e"
original_class_hash = "0x1db14cac86795ac0ff8dac3d7e426273d98e209007288169b9d8353bcbdd0e"
abi = "manifests/dev/deployment/abis/models/haiku-PromptMessage-461b562f.json"
tag = "haiku-PromptMessage"
qualified_path = "haiku_event::prompt_message"
manifest_name = "haiku-PromptMessage-461b562f"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "event_id"
type = "u32"
key = true

[[models.members]]
name = "event_tag"
type = "ByteArray"
key = false

[[models.members]]
name = "prompt"
type = "ByteArray"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x72e2f8b7ff645d6eb887cc8d1842bd4abb7efe2eac319e40f313cf8b0349793"
original_class_hash = "0x72e2f8b7ff645d6eb887cc8d1842bd4abb7efe2eac319e40f313cf8b0349793"
abi = "manifests/dev/deployment/abis/models/haiku-SpawnEvent-aa8d3a37.json"
tag = "haiku-SpawnEvent"
qualified_path = "rpg::components::playable::PlayableComponent::spawn_event"
manifest_name = "haiku-SpawnEvent-aa8d3a37"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "player_role"
type = "u8"
key = false

[[models.members]]
name = "player_mode"
type = "u8"
key = false

[[models.members]]
name = "player_health"
type = "u8"
key = false

[[models.members]]
name = "player_gold"
type = "u16"
key = false

[[models.members]]
name = "player_score"
type = "u16"
key = false

[[models.members]]
name = "player_name"
type = "felt252"
key = false
