kind = "DojoModel"
class_hash = "0x4b62eaf8033fe92627f262746bb8ee57dd8f932c92fea35fd3f3fefc18a573d"
original_class_hash = "0x4b62eaf8033fe92627f262746bb8ee57dd8f932c92fea35fd3f3fefc18a573d"
abi = "manifests/dev/base/abis/models/haiku-AttackEvent-7bdb02fd.json"
tag = "haiku-AttackEvent"
qualified_path = "rpg::components::playable::PlayableComponent::attack_event"
manifest_name = "haiku-AttackEvent-7bdb02fd"

[[members]]
name = "player_id"
type = "felt252"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "timestamp"
type = "u64"
key = false

[[members]]
name = "player_role"
type = "u8"
key = false

[[members]]
name = "player_mode"
type = "u8"
key = false

[[members]]
name = "player_health"
type = "u8"
key = false

[[members]]
name = "player_gold"
type = "u16"
key = false

[[members]]
name = "player_score"
type = "u16"
key = false

[[members]]
name = "player_name"
type = "felt252"
key = false

[[members]]
name = "dungeon_monster"
type = "u8"
key = false

[[members]]
name = "dungeon_role"
type = "u8"
key = false

[[members]]
name = "dungeon_damage"
type = "u8"
key = false

[[members]]
name = "dungeon_health"
type = "u8"
key = false

[[members]]
name = "dungeon_reward"
type = "u16"
key = false

[[members]]
name = "has_defeated_dungeon"
type = "bool"
key = false
